apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dripday-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dripday.co    
    secretName: dripday-tls  
  rules:
  - host: dripday.co     
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dripday-web-app-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: dripday-api-user
            port:
              number: 3000
